/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FiveQueens;
import java.util.ArrayList;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
/**
 *
 * @author Msys
 */
public class fiveQueensJFrame extends javax.swing.JFrame {

    /**
     * Creates new form fiveQueensJFrame
     */
    state current;

    public fiveQueensJFrame() {
        initComponents();
        setSize(800,800);
        setLocationRelativeTo(null);
        current =new state();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel27 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jbexit = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jb00 = new javax.swing.JButton();
        jb01 = new javax.swing.JButton();
        jb02 = new javax.swing.JButton();
        jb03 = new javax.swing.JButton();
        jb04 = new javax.swing.JButton();
        jb10 = new javax.swing.JButton();
        jb11 = new javax.swing.JButton();
        jb12 = new javax.swing.JButton();
        jb13 = new javax.swing.JButton();
        jb14 = new javax.swing.JButton();
        jb20 = new javax.swing.JButton();
        jb21 = new javax.swing.JButton();
        jb22 = new javax.swing.JButton();
        jb23 = new javax.swing.JButton();
        jb24 = new javax.swing.JButton();
        jb30 = new javax.swing.JButton();
        jb31 = new javax.swing.JButton();
        jb32 = new javax.swing.JButton();
        jb33 = new javax.swing.JButton();
        jb34 = new javax.swing.JButton();
        jb40 = new javax.swing.JButton();
        jb41 = new javax.swing.JButton();
        jb42 = new javax.swing.JButton();
        jb43 = new javax.swing.JButton();
        jb44 = new javax.swing.JButton();

        jLabel27.setText("jLabel27");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("5 Queens");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel1.setFont(new java.awt.Font("Segoe UI", 0, 90)); // NOI18N

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 90)); // NOI18N
        jLabel1.setText("5 Queens");
        jPanel1.add(jLabel1);
        jLabel1.getAccessibleContext().setAccessibleName("5 Qweens");

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jButton1.setBackground(new java.awt.Color(255, 255, 204));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton1.setText("Sort");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 51), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);

        jButton2.setBackground(new java.awt.Color(255, 255, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton2.setText("Random Reset");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);

        jButton4.setBackground(new java.awt.Color(255, 255, 204));
        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jButton4.setText("Clear");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 153, 0), 2));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);

        jbexit.setBackground(new java.awt.Color(255, 255, 204));
        jbexit.setFont(new java.awt.Font("Segoe UI", 0, 48)); // NOI18N
        jbexit.setText("Exit");
        jbexit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 153, 0), 2, true));
        jbexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbexitActionPerformed(evt);
            }
        });
        jPanel2.add(jbexit);

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jPanel3.setLayout(new java.awt.GridLayout(5, 5));

        jb00.setBackground(new java.awt.Color(153, 255, 153));
        jb00.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb00.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb00ActionPerformed(evt);
            }
        });
        jPanel3.add(jb00);

        jb01.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb01ActionPerformed(evt);
            }
        });
        jPanel3.add(jb01);

        jb02.setBackground(new java.awt.Color(153, 255, 153));
        jb02.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb02.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb02ActionPerformed(evt);
            }
        });
        jPanel3.add(jb02);

        jb03.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb03.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb03ActionPerformed(evt);
            }
        });
        jPanel3.add(jb03);

        jb04.setBackground(new java.awt.Color(153, 255, 153));
        jb04.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb04.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb04ActionPerformed(evt);
            }
        });
        jPanel3.add(jb04);

        jb10.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb10ActionPerformed(evt);
            }
        });
        jPanel3.add(jb10);

        jb11.setBackground(new java.awt.Color(153, 255, 153));
        jb11.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb11ActionPerformed(evt);
            }
        });
        jPanel3.add(jb11);

        jb12.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb12ActionPerformed(evt);
            }
        });
        jPanel3.add(jb12);

        jb13.setBackground(new java.awt.Color(153, 255, 153));
        jb13.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb13ActionPerformed(evt);
            }
        });
        jPanel3.add(jb13);

        jb14.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb14ActionPerformed(evt);
            }
        });
        jPanel3.add(jb14);

        jb20.setBackground(new java.awt.Color(153, 255, 153));
        jb20.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb20ActionPerformed(evt);
            }
        });
        jPanel3.add(jb20);

        jb21.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb21ActionPerformed(evt);
            }
        });
        jPanel3.add(jb21);

        jb22.setBackground(new java.awt.Color(153, 255, 153));
        jb22.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb22ActionPerformed(evt);
            }
        });
        jPanel3.add(jb22);

        jb23.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb23ActionPerformed(evt);
            }
        });
        jPanel3.add(jb23);

        jb24.setBackground(new java.awt.Color(153, 255, 153));
        jb24.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb24ActionPerformed(evt);
            }
        });
        jPanel3.add(jb24);

        jb30.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb30ActionPerformed(evt);
            }
        });
        jPanel3.add(jb30);

        jb31.setBackground(new java.awt.Color(153, 255, 153));
        jb31.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb31ActionPerformed(evt);
            }
        });
        jPanel3.add(jb31);

        jb32.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb32ActionPerformed(evt);
            }
        });
        jPanel3.add(jb32);

        jb33.setBackground(new java.awt.Color(153, 255, 153));
        jb33.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb33ActionPerformed(evt);
            }
        });
        jPanel3.add(jb33);

        jb34.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb34ActionPerformed(evt);
            }
        });
        jPanel3.add(jb34);

        jb40.setBackground(new java.awt.Color(153, 255, 153));
        jb40.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb40ActionPerformed(evt);
            }
        });
        jPanel3.add(jb40);

        jb41.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb41ActionPerformed(evt);
            }
        });
        jPanel3.add(jb41);

        jb42.setBackground(new java.awt.Color(153, 255, 153));
        jb42.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb42ActionPerformed(evt);
            }
        });
        jPanel3.add(jb42);

        jb43.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb43ActionPerformed(evt);
            }
        });
        jPanel3.add(jb43);

        jb44.setBackground(new java.awt.Color(153, 255, 153));
        jb44.setFont(new java.awt.Font("Segoe UI", 0, 50)); // NOI18N
        jb44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb44ActionPerformed(evt);
            }
        });
        jPanel3.add(jb44);

        getContentPane().add(jPanel3, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    private JFrame frame;
    void updateCurrent (int i,int j,int bit)
    {
        current.m[i][j]=bit;
    }

    private void jb03ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb03ActionPerformed
        // TODO add your handling code here:
        if (jb03.getText()== "")
        {
            jb03.setText("Q");
            updateCurrent(0,3,1);
        }

        else
        {
            jb03.setText("");
            updateCurrent(0,3,0);
        }

    }//GEN-LAST:event_jb03ActionPerformed

    private void jb33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb33ActionPerformed
        // TODO add your handling code here:
         if (jb33.getText()== "")
         {
             jb33.setText("Q");
             updateCurrent(3,3,1);
         }

        else
         {
             jb33.setText("");
              updateCurrent(3,3,0);
         }

    }//GEN-LAST:event_jb33ActionPerformed

    private void jb00ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb00ActionPerformed
        // TODO add your handling code here:
         if (jb00.getText()== "")
         {
             jb00.setText("Q");
             updateCurrent(0,0,1);
         }

        else
         {
             jb00.setText("");
              updateCurrent(0,0,0);
         }

    }//GEN-LAST:event_jb00ActionPerformed

    private void jb01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb01ActionPerformed
        // TODO add your handling code here:
        if (jb01.getText()== "")
        {
             jb01.setText("Q");
             updateCurrent(0,1,1);
        }

        else
        {
            jb01.setText("");
             updateCurrent(0,1,0);
        }

    }//GEN-LAST:event_jb01ActionPerformed

    private void jb02ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb02ActionPerformed
        // TODO add your handling code here:
        if (jb02.getText()== "")
        {
             jb02.setText("Q");
             updateCurrent(0,2,1);
        }

        else
        {
            jb02.setText("");
             updateCurrent(0,2,0);
        }

    }//GEN-LAST:event_jb02ActionPerformed

    private void jb04ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb04ActionPerformed
        // TODO add your handling code here:
        if (jb04.getText()== "")
        {
            jb04.setText("Q");
            updateCurrent(0,4,1);
        }

        else
        {
           jb04.setText("");
           updateCurrent(0,4,0);

        }

    }//GEN-LAST:event_jb04ActionPerformed

    private void jb10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb10ActionPerformed
        // TODO add your handling code here:
        if (jb10.getText()== "")
        {
            jb10.setText("Q");
            updateCurrent(1,0,1);
        }

        else
        {
            jb10.setText("");
            updateCurrent(1,0,0);
        }

    }//GEN-LAST:event_jb10ActionPerformed

    private void jb11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb11ActionPerformed
        // TODO add your handling code here:
        if (jb11.getText()== "")
        {
            jb11.setText("Q");
            updateCurrent(1,1,1);
        }

        else
        {
             jb11.setText("");
             updateCurrent(1,1,0);
        }

    }//GEN-LAST:event_jb11ActionPerformed

    private void jb12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb12ActionPerformed
        // TODO add your handling code here:
          if (jb12.getText()== "")
          {
              jb12.setText("Q");
              updateCurrent(1,2,1);
          }

        else
          {
              jb12.setText("");
              updateCurrent(1,2,0);
          }

    }//GEN-LAST:event_jb12ActionPerformed

    private void jb13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb13ActionPerformed
        // TODO add your handling code here:
         if (jb13.getText()== "")
         {
             jb13.setText("Q");
             updateCurrent(1,3,1);
         }

        else
         {
              jb13.setText("");
              updateCurrent(1,3,0);
         }

    }//GEN-LAST:event_jb13ActionPerformed

    private void jb14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb14ActionPerformed
        // TODO add your handling code here:
        if (jb14.getText()== "")
        {
            jb14.setText("Q");
            updateCurrent(1,4,1);
        }

        else
        {
             jb14.setText("");
             updateCurrent(1,4,0);
        }

    }//GEN-LAST:event_jb14ActionPerformed

    private void jb20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb20ActionPerformed
        // TODO add your handling code here:
         if (jb20.getText()== "")
         {
             jb20.setText("Q");
             updateCurrent(2,0,1);
         }

        else
         {
             jb20.setText("");
             updateCurrent(2,0,0);
         }

    }//GEN-LAST:event_jb20ActionPerformed

    private void jb21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb21ActionPerformed
        // TODO add your handling code here:
         if (jb21.getText()== "")
         {
              jb21.setText("Q");
               updateCurrent(2,1,1);
         }

        else
         {
              jb21.setText("");
              updateCurrent(2,1,0);
         }

    }//GEN-LAST:event_jb21ActionPerformed

    private void jb22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb22ActionPerformed
        // TODO add your handling code here:
         if (jb22.getText()== "")
         {
              jb22.setText("Q");
              updateCurrent(2,2,1);
         }

        else
         {
             jb22.setText("");
             updateCurrent(2,2,0);
         }
    }//GEN-LAST:event_jb22ActionPerformed

    private void jb23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb23ActionPerformed
        // TODO add your handling code here:
        if (jb23.getText()== "")
        {
            jb23.setText("Q");
            updateCurrent(2,3,1);
        }
        else
        {
            jb23.setText("");
            updateCurrent(2,3,0);
        }
    }//GEN-LAST:event_jb23ActionPerformed

    private void jb24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb24ActionPerformed
        // TODO add your handling code here:
        if (jb24.getText()== "")
        {
            jb24.setText("Q");
            updateCurrent(2,4,1);
        }
        else
        {
            jb24.setText("");
            updateCurrent(2,4,0);
        }
    }//GEN-LAST:event_jb24ActionPerformed

    private void jb30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb30ActionPerformed
        // TODO add your handling code here:
         if (jb30.getText()== "")
         {
             jb30.setText("Q");
              updateCurrent(3,0,1);
         }
        else
         {
             jb30.setText("");
             updateCurrent(3,0,0);
         }
    }//GEN-LAST:event_jb30ActionPerformed

    private void jb31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb31ActionPerformed
        // TODO add your handling code here:
         if (jb31.getText()== "")
         {
             jb31.setText("Q");
             updateCurrent(3,1,1);
         }
        else
         {
             jb31.setText("");
              updateCurrent(3,1,0);
         }
    }//GEN-LAST:event_jb31ActionPerformed

    private void jb32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb32ActionPerformed
        // TODO add your handling code here:
        if (jb32.getText()== "")
        {
            jb32.setText("Q");
            updateCurrent(3,2,1);
        }
        else
        {
            jb32.setText("");
             updateCurrent(3,2,0);
        }
    }//GEN-LAST:event_jb32ActionPerformed

    private void jb34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb34ActionPerformed
        // TODO add your handling code here:
        if (jb34.getText()== "")
        {
            jb34.setText("Q");
            updateCurrent(3,4,1);
        }
        else
        {
            jb34.setText("");
            updateCurrent(3,4,0);
        }
    }//GEN-LAST:event_jb34ActionPerformed

    private void jb40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb40ActionPerformed
        // TODO add your handling code here:
          if (jb40.getText()== "")
          {
              jb40.setText("Q");
              updateCurrent(4,0,1);
          }
        else
          {
              jb40.setText("");
               updateCurrent(4,0,0);
          }
    }//GEN-LAST:event_jb40ActionPerformed

    private void jb41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb41ActionPerformed
        // TODO add your handling code here:
          if (jb41.getText()== "")
          {
              jb41.setText("Q");
              updateCurrent(4,1,1);
          }
        else
          {
              jb41.setText("");
              updateCurrent(4,1,0);
          }
    }//GEN-LAST:event_jb41ActionPerformed

    private void jb42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb42ActionPerformed
        // TODO add your handling code here:
         if (jb42.getText()== "")
         {
             jb42.setText("Q");
             updateCurrent(4,2,1);
         }
        else
         {
             jb42.setText("");
             updateCurrent(4,2,0);
         }
    }//GEN-LAST:event_jb42ActionPerformed

    private void jb43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb43ActionPerformed
        // TODO add your handling code here:
         if (jb43.getText()== "")
         {
             jb43.setText("Q");
             updateCurrent(4,3,1);
         }
        else
         {
             jb43.setText("");
              updateCurrent(4,3,0);
         }
    }//GEN-LAST:event_jb43ActionPerformed

    private void jb44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb44ActionPerformed
        // TODO add your handling code here:
         if (jb44.getText()== "")
         {
             jb44.setText("Q");
             updateCurrent(4,4,1);
         }
        else
         {
             jb44.setText("");
             updateCurrent(4,4,0);
         }
    }//GEN-LAST:event_jb44ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Simulated_Annealing_Algo sm=new Simulated_Annealing_Algo();
        state solution = new state();
        try {
            solution=sm.Sim_Anneal(current);
        } catch (CloneNotSupportedException ex) {
            Logger.getLogger(fiveQueensJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
  
        if(solution.m[0][0]==1)
        {
            jb00.setText("Q");
        }
        else
            jb00.setText("");
        
         if(solution.m[0][1]==1)
        {
            jb01.setText("Q");
        }
        else
            jb01.setText("");
         
         
         if(solution.m[0][2]==1)
        {
            jb02.setText("Q");
        }
        else
            jb02.setText("");
         
         
         if(solution.m[0][3]==1)
        {
            jb03.setText("Q");
        }
        else
            jb03.setText("");
         
         
         
         if(solution.m[0][4]==1)
        {
            jb04.setText("Q");
        }
        else
            jb04.setText("");
         
         
         
         if(solution.m[1][0]==1)
        {
            jb10.setText("Q");
        }
        else
            jb10.setText("");
         
         
         
           if(solution.m[1][1]==1)
        {
            jb11.setText("Q");
        }
        else
            jb11.setText("");
           
           
           
          if(solution.m[1][2]==1)
        {
            jb12.setText("Q");
        }
        else
            jb12.setText("");
          
          
          
           if(solution.m[1][3]==1)
        {
            jb13.setText("Q");
        }
        else
            jb13.setText("");
           
           
           
           
           if(solution.m[1][4]==1)
        {
            jb14.setText("Q");
        }
        else
            jb14.setText("");
           
           
           
             if(solution.m[2][0]==1)
        {
            jb20.setText("Q");
        }
        else
            jb20.setText("");
             
             
              if(solution.m[2][1]==1)
        {
            jb21.setText("Q");
        }
        else
            jb21.setText("");
           
              
              
              
               if(solution.m[2][2]==1)
        {
            jb22.setText("Q");
        }
        else
            jb22.setText("");
               
               
               
               
                if(solution.m[2][3]==1)
        {
            jb23.setText("Q");
        }
        else
            jb23.setText("");
                
                
                
                 if(solution.m[2][4]==1)
        {
            jb24.setText("Q");
        }
        else
            jb24.setText("");
                
                 
                 
                 if(solution.m[3][0]==1)
        {
            jb30.setText("Q");
        }
        else
            jb30.setText("");
                 
                 
                  if(solution.m[3][1]==1)
        {
            jb31.setText("Q");
        }
        else
            jb31.setText("");
                 
                  
                  if(solution.m[3][2]==1)
        {
            jb32.setText("Q");
        }
        else
            jb32.setText("");
                  
                  
                  
                   if(solution.m[3][3]==1)
        {
            jb33.setText("Q");
        }
        else
            jb33.setText("");
                   
                   
                    if(solution.m[3][4]==1)
        {
            jb34.setText("Q");
        }
        else
            jb34.setText("");
                 
                    
                    
                     if(solution.m[4][0]==1)
        {
            jb40.setText("Q");
        }
        else
            jb40.setText("");
                     
                     
                     
                      if(solution.m[4][1]==1)
        {
            jb41.setText("Q");
        }
        else
            jb41.setText("");
                
                
                
                
            if(solution.m[4][2]==1)
        {
            jb42.setText("Q");
        }
        else
            jb42.setText("");
           
            
            
            
             if(solution.m[4][3]==1)
        {
            jb43.setText("Q");
        }
        else
            jb43.setText("");
             
             
             
              if(solution.m[4][4]==1)
        {
            jb44.setText("Q");
        }
        else
            jb44.setText("");
           
           


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
     int  randomRow[]=new int [5];       
     state randomState=new state();    
      Random r =new Random();
      
     for(int y=0;y<5;y++)
     {
        
         randomRow[y]=r.nextInt(5);
         
     }
     
     
     
     if(randomRow[0]==0)
     {
         jb00.setText("Q");
          updateCurrent(0,0,1);
     }
         
         else
     {
          jb00.setText("");
           updateCurrent(0,0,0);
     }
        
     
     if(randomRow[0]==1)
        {
         jb10.setText("Q");
          updateCurrent(1,0,1);
     }
         
         else
     {
          jb10.setText("");
           updateCurrent(1,0,0);
     }
     
     
      if(randomRow[0]==2)
        {
         jb20.setText("Q");
          updateCurrent(2,0,1);
     }
         
         else
     {
          jb20.setText("");
           updateCurrent(2,0,0);
     }
     
      
      
       if(randomRow[0]==3)
        {
         jb30.setText("Q");
          updateCurrent(3,0,1);
     }
         
         else
     {
          jb30.setText("");
           updateCurrent(3,0,0);
     }
       
       
       
       
        if(randomRow[0]==4)
        {
         jb40.setText("Q");
          updateCurrent(4,0,1);
     }
         
         else
     {
          jb40.setText("");
           updateCurrent(4,0,0);
     }
        
        
        
        
         if(randomRow[1]==0)
        {
         jb01.setText("Q");
          updateCurrent(0,1,1);
     }
         
         else
     {
          jb01.setText("");
           updateCurrent(0,1,0);
     }
        
     
         
       if(randomRow[1]==1)
        {
         jb11.setText("Q");
          updateCurrent(1,1,1);
     }
         
         else
     {
          jb11.setText("");
           updateCurrent(1,1,0);
     }
       
       
        if(randomRow[1]==2)
        {
         jb21.setText("Q");
          updateCurrent(2,1,1);
     }
         
         else
     {
          jb21.setText("");
           updateCurrent(2,1,0);
     }
         
        
        
         if(randomRow[1]==3)
        {
         jb31.setText("Q");
          updateCurrent(3,1,1);
     }
         
         else
     {
          jb31.setText("");
           updateCurrent(3,1,0);
     }
         
         
         
          if(randomRow[1]==4)
        {
         jb41.setText("Q");
          updateCurrent(4,1,1);
     }
         
         else
     {
          jb41.setText("");
           updateCurrent(4,1,0);
     }
          
          
          
          
            if(randomRow[2]==0)
        {
         jb02.setText("Q");
          updateCurrent(0,2,1);
     }
         
         else
     {
          jb02.setText("");
           updateCurrent(0,2,0);
     }
         
          
          if(randomRow[2]==1)
        {
         jb12.setText("Q");
          updateCurrent(1,2,1);
     }
         
         else
     {
          jb12.setText("");
           updateCurrent(1,2,0);
     }  
          
          
          
           if(randomRow[2]==2)
        {
         jb22.setText("Q");
          updateCurrent(2,2,1);
     }
         
         else
     {
          jb22.setText("");
           updateCurrent(2,2,0);
     }  
           
           
           
             if(randomRow[2]==3)
        {
         jb32.setText("Q");
          updateCurrent(3,2,1);
     }
         
         else
     {
          jb32.setText("");
           updateCurrent(3,2,0);
     }  
          
          if(randomRow[2]==4)
        {
         jb42.setText("Q");
          updateCurrent(4,2,1);
     }
         
         else
     {
          jb42.setText("");
           updateCurrent(4,2,0);
     }  
         
          
          
           if(randomRow[3]==0)
        {
         jb03.setText("Q");
          updateCurrent(0,3,1);
     }
         
         else
     {
          jb03.setText("");
           updateCurrent(0,3,0);
     }  
           
           
           
           
              if(randomRow[3]==1)
        {
         jb13.setText("Q");
          updateCurrent(1,3,1);
     }
         
         else
     {
          jb13.setText("");
           updateCurrent(1,3,0);
     }  
              
              
    if(randomRow[3]==2)
        {
         jb23.setText("Q");
          updateCurrent(2,3,1);
     }
         
         else
     {
          jb23.setText("");
           updateCurrent(2,3,0);
     }            
              
             
    
    
     if(randomRow[3]==3)
        {
         jb33.setText("Q");
          updateCurrent(3,3,1);
     }
         
         else
     {
          jb33.setText("");
           updateCurrent(3,3,0);
     }           
     
     
     
     
     if(randomRow[3]==4)
        {
         jb43.setText("Q");
          updateCurrent(4,3,1);
     }
         
         else
     {
          jb43.setText("");
           updateCurrent(4,3,0);
     }            
              

     
       if(randomRow[4]==0)
        {
         jb04.setText("Q");
          updateCurrent(0,4,1);
     }
         
         else
     {
          jb04.setText("");
           updateCurrent(0,4,0);
     }            
       
       
        if(randomRow[4]==1)
        {
         jb14.setText("Q");
          updateCurrent(1,4,1);
     }
         
         else
     {
          jb14.setText("");
           updateCurrent(1,4,0);
     }            
       
        
           if(randomRow[4]==2)
        {
         jb24.setText("Q");
          updateCurrent(2,4,1);
     }
         
         else
     {
          jb24.setText("");
           updateCurrent(2,4,0);
     }            
       
         if(randomRow[4]==3)
        {
         jb34.setText("Q");
          updateCurrent(3,4,1);
     }
         
         else
     {
          jb34.setText("");
           updateCurrent(3,4,0);
     }             
     
         
           if(randomRow[4]==4)
        {
         jb44.setText("Q");
          updateCurrent(4,4,1);
     }
         
         else
     {
          jb44.setText("");
           updateCurrent(4,4,0);
     }             
     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        jb00.setText("");
        updateCurrent(0,0,0);
        
         jb01.setText("");
        updateCurrent(0,1,0);
        
        jb02.setText("");
        updateCurrent(0,2,0);
        
         jb03.setText("");
        updateCurrent(0,3,0);
        
         jb04.setText("");
        updateCurrent(0,4,0);
        
        
        
        jb10.setText("");
        updateCurrent(1,0,0);
        
         jb11.setText("");
        updateCurrent(1,1,0);
        
        jb12.setText("");
        updateCurrent(1,2,0);
        
         jb13.setText("");
        updateCurrent(1,3,0);
        
         jb14.setText("");
        updateCurrent(1,4,0);
        
        
        
        
        jb20.setText("");
        updateCurrent(2,0,0);
        
         jb21.setText("");
        updateCurrent(2,1,0);
        
        jb22.setText("");
        updateCurrent(2,2,0);
        
         jb23.setText("");
        updateCurrent(2,3,0);
        
         jb24.setText("");
        updateCurrent(2,4,0);
        
        
        
        jb30.setText("");
        updateCurrent(3,0,0);
        
         jb31.setText("");
        updateCurrent(3,1,0);
        
        jb32.setText("");
        updateCurrent(3,2,0);
        
         jb33.setText("");
        updateCurrent(3,3,0);
        
         jb34.setText("");
        updateCurrent(3,4,0);
        
        
        
        
         jb40.setText("");
        updateCurrent(4,0,0);
        
         jb41.setText("");
        updateCurrent(4,1,0);
        
        jb42.setText("");
        updateCurrent(4,2,0);
        
         jb43.setText("");
        updateCurrent(4,3,0);
        
         jb44.setText("");
        updateCurrent(4,4,0);
        
        
        
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jbexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbexitActionPerformed
        // TODO add your handling code here:
        frame=new JFrame("Exit");
        
        
        if(JOptionPane.showConfirmDialog(frame, "Confirm if you want to exit","5 Queens", 
                JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION)
            {
            System.exit(0);
        }
            
            
       
        
        
    }//GEN-LAST:event_jbexitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(fiveQueensJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(fiveQueensJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(fiveQueensJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(fiveQueensJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new fiveQueensJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jb00;
    private javax.swing.JButton jb01;
    private javax.swing.JButton jb02;
    private javax.swing.JButton jb03;
    private javax.swing.JButton jb04;
    private javax.swing.JButton jb10;
    private javax.swing.JButton jb11;
    private javax.swing.JButton jb12;
    private javax.swing.JButton jb13;
    private javax.swing.JButton jb14;
    private javax.swing.JButton jb20;
    private javax.swing.JButton jb21;
    private javax.swing.JButton jb22;
    private javax.swing.JButton jb23;
    private javax.swing.JButton jb24;
    private javax.swing.JButton jb30;
    private javax.swing.JButton jb31;
    private javax.swing.JButton jb32;
    private javax.swing.JButton jb33;
    private javax.swing.JButton jb34;
    private javax.swing.JButton jb40;
    private javax.swing.JButton jb41;
    private javax.swing.JButton jb42;
    private javax.swing.JButton jb43;
    private javax.swing.JButton jb44;
    private javax.swing.JButton jbexit;
    // End of variables declaration//GEN-END:variables
}
